rbapat - Created merchandise page with navigation to it at top of home page
gmundewadi/coderssb-website pull request #17
Opened 2020-08-30 04:55 UTC by minibapat

2020-09-12 20:08 UTC, gmundewadi requested changes

2020-09-12 20:08 UTC, gmundewadi commented on pages/merchandisePage.js
> +export default function merchandisePage() {
PascalCase the page name

2020-09-12 20:08 UTC, gmundewadi commented on components/Page_Layout/Merchandise.js
> +export default function Merchandise() {
also, make sure that your commit messages describe the feature that you are adding. Kinda like making a roadmap of what you’ve done in the past :)

2020-09-13 05:43 UTC, merged

2020-10-07 18:33 UTC, minibapat commented on components/Page_Layout/Merchandise.js
> +        <img
resolved