Make Calendar events clickable
gmundewadi/coderssb-website pull request #24
Opened 2020-09-19 04:24 UTC by shirlyntang

2020-09-20 18:29 UTC, gmundewadi requested changes

2020-09-20 18:29 UTC, gmundewadi commented on components/Page_Layout/CustomEvent.js
> +        <h8 onClick={this.handleClick}>
lets add a onHover css property here to highlight the event

2020-09-20 18:29 UTC, gmundewadi commented on utils/events.js
>    {
add a link to the Date object documentation at the top of this file for future officers

2020-09-22 13:26 UTC, shirlyntang commented
Added capabilities for text color change on hover. Added Date object documentation link. Also deleted a css file since it wasn't used.

2020-09-22 18:37 UTC, gmundewadi commented on components/Page_Layout/CustomEvent.js
> +	      linkStyle = {color: 'black'};
to match the theme, set the hover color to `rgb(250, 176, 60)`

2020-09-22 18:43 UTC, gmundewadi commented on components/Page_Layout/CustomEvent.js
> +        <h8 style={linkStyle} onMouseEnter={this.toggleHover} onMouseLeave={this.toggleHover} onClick={this.handleClick}>
is there any way to set the color of the event to `rgb(144, 215, 241)`

2020-09-22 18:44 UTC, gmundewadi requested changes
two small color changes for the event. Everything else looks great

2020-09-23 23:06 UTC, minibapat approved these changes

2020-09-23 23:06 UTC, sriya112 approved these changes

2020-09-25 19:33 UTC, shirlyntang commented
Keeping white/black colors since it goes better with the calendar events color that I don't think I can change!

2020-09-25 19:34 UTC, merged